import type { Metadata } from "next";

import "./globals.css";
import Link from "next/link";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="flex justify-end items-center font-bold text-xl gap-4 p-4 bg-red-200 text-black">
          <div className="text-sm">
          <Link href="/login">Login</Link> |
          <Link href="/register">Register</Link>
          </div>
        </header>
        <main className="min-h-[80vh] bg-blue-50 text-black">
          {children}
        </main>
        <footer className="">Copyright isn&apos;t reserved</footer>
      </body>
    </html>
  );
}
